import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header/Header";
import { MenuProvider } from "@/contexts/menuContext/menuContext";
import { MenuNav } from "@/components/MenuNav/MenuNav";
import { PageTransition } from "@/components/PageTransition/PageTransition";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "Jhonatan's Portfolio",
    template: "%s | Jhonatan's Portfolio"
  },
  description: "Generated by create next app",
  icons: [
    "/logo.png?v=4"
  ]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <MenuProvider>
        <body className={montserrat.className}>
          {/* <PageTransition /> */}
          <Header />
          <MenuNav />
          {children}
        </body>
      </MenuProvider>
    </html>
  );
}
