import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Header";
import { MenuNav } from "@/components/MenuNav/MenuNav";
import { PageTransition } from "@/components/PageTransition/PageTransition";
import { MenuProvider } from "@/lib/contexts/menuContext/menuContext";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { montserrat } from "@/assets";
import { WhatsappButtonFixed } from "@/components/WhatsappButtonFixed";

export const metadata: Metadata = {
  title: {
    absolute: "Jhonatan's Portfolio",
    template: "%s | Jhonatan's Portfolio"
  },
  description: "Generated by create next app",
  icons: [
    "/logo.png?v=4"
  ]
};

export default async function LocaleLayout({
  children,
  params: { locale }
}: {
  children: React.ReactNode;
  params: { locale: string };

}) {

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`${montserrat.className}`}>

        <NextIntlClientProvider messages={messages}>

          <MenuProvider>
            <PageTransition />
            <Header />
            <MenuNav />
            {children}
            <WhatsappButtonFixed />
          </MenuProvider>

        </NextIntlClientProvider>

      </body>
    </html>
  );
}