import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Header";
import { MenuNav } from "@/components/MenuNav/MenuNav";
import { PageTransition } from "@/components/PageTransition/PageTransition";
import { AuthProvider } from "@/lib/contexts/authContext.tsx/AuthContext";
import { MenuProvider } from "@/lib/contexts/menuContext/menuContext";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { montserrat } from "@/assets";

export const metadata: Metadata = {
  title: {
    default: "Jhonatan's Portfolio",
    template: "%s | Jhonatan's Portfolio"
  },
  description: "Generated by create next app",
  icons: [
    "/logo.png?v=4"
  ]
};

export default async function LocaleLayout({
  children,
  params: { locale }
}: {
  children: React.ReactNode;
  params: { locale: string };

}) {

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`${montserrat.className}`}>

        <NextIntlClientProvider messages={messages}>
          <AuthProvider>
            <MenuProvider>
              {/* <PageTransition /> */}
              <Header />
              <MenuNav />
              {children}
            </MenuProvider>
          </AuthProvider>
        </NextIntlClientProvider>

      </body>
    </html>
  );
}